# Generated by Django 4.2.4 on 2023-12-27 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='userid',
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
    ]
